// Generate migrations/seed-reference.sql from the fixtures. This seeds the
// shared global food/recipe catalog — used one-time for prod and re-runnable
// locally. Tests seed small subsets directly via src/seed.ts instead.
//
//   node scripts/gen-seed.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const ref = join(root, "fixtures", "reference");
const foods = JSON.parse(readFileSync(join(ref, "foods.json"), "utf8"));
const recipes = JSON.parse(readFileSync(join(ref, "recipes.json"), "utf8"));
const categories = JSON.parse(readFileSync(join(ref, "food-categories.json"), "utf8"));

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const slug = (s) =>
  String(s).toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "cat";

const lines = ["-- GENERATED by scripts/gen-seed.mjs — do not edit by hand.", "BEGIN TRANSACTION;"];
// Idempotent: clear the reference catalog first so re-seeding is safe.
for (const t of ["recipe_ingredient", "recipe_caption", "recipe", "food_caption", "food", "food_category"]) {
  lines.push(`DELETE FROM ${t};`);
}

// categories
const catId = new Map();
categories.forEach((name, i) => {
  catId.set(name, i + 1);
  lines.push(`INSERT INTO food_category (id,key,label,sort_order) VALUES (${i + 1},${q(slug(name))},${q(name)},${i});`);
});

// foods (+ caption in source locale)
const foodId = new Map();
foods.forEach((f, i) => {
  const id = i + 1;
  foodId.set(f.name, id);
  lines.push(
    `INSERT INTO food (id,category_id,kcal_100g,protein_100g,fat_100g,carb_100g,scope,source_locale) ` +
      `VALUES (${id},${catId.get(f.category) ?? "NULL"},${f.kcal_100g},${f.protein_100g},${f.fat_100g},${f.carb_100g},'global',${q(f.source_locale)});`,
  );
  lines.push(`INSERT INTO food_caption (food_id,locale,caption) VALUES (${id},${q(f.source_locale)},${q(f.name)});`);
});

// recipes (+ caption + ingredients). Skip ingredients whose food is unknown.
let missing = 0;
recipes.forEach((r, i) => {
  const id = i + 1;
  lines.push(
    `INSERT INTO recipe (id,cat1,cat2,cat3,servings,scope,source_locale) ` +
      `VALUES (${id},${q(r.cat1)},${q(r.cat2)},${q(r.cat3)},${r.servings},'global',${q(r.source_locale)});`,
  );
  lines.push(`INSERT INTO recipe_caption (recipe_id,locale,caption) VALUES (${id},${q(r.source_locale)},${q(r.name)});`);
  r.ingredients.forEach((ing, pos) => {
    const fid = foodId.get(ing.food);
    if (!fid) { missing++; return; }
    lines.push(
      `INSERT INTO recipe_ingredient (recipe_id,food_id,min_g,max_g,position) ` +
        `VALUES (${id},${fid},${ing.min_g},${ing.max_g},${pos});`,
    );
  });
});

lines.push("COMMIT;");
writeFileSync(join(root, "migrations", "seed-reference.sql"), lines.join("\n") + "\n");
console.error(`wrote seed: ${categories.length} categories, ${foods.length} foods, ${recipes.length} recipes` +
  (missing ? ` (${missing} ingredient rows skipped: food not in catalog)` : ""));
