// Seed the shared global catalog into a D1 database from fixture arrays. Tests
// call this with small subsets; prod uses migrations/seed-reference.sql (same
// data, generated by scripts/gen-seed.mjs).

export interface FoodSeed {
  name: string;
  category: string;
  kcal_100g: number;
  protein_100g: number;
  fat_100g: number;
  carb_100g: number;
  source_locale: string;
}
export interface RecipeSeed {
  name: string;
  cat1: string;
  cat2: string;
  cat3: string;
  servings: number;
  source_locale: string;
  ingredients: { food: string; min_g: number; max_g: number }[];
}
export interface SeedData {
  categories: string[];
  foods: FoodSeed[];
  recipes: RecipeSeed[];
}

const slug = (s: string) =>
  s.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "cat";

export async function seedReference(db: D1Database, data: SeedData) {
  const catId = new Map<string, number>();
  for (let i = 0; i < data.categories.length; i++) {
    const name = data.categories[i];
    const r = await db
      .prepare("INSERT INTO food_category (key,label,sort_order) VALUES (?,?,?) RETURNING id")
      .bind(slug(name), name, i)
      .first<{ id: number }>();
    catId.set(name, r!.id);
  }

  const foodId = new Map<string, number>();
  for (const f of data.foods) {
    const r = await db
      .prepare(
        "INSERT INTO food (category_id,kcal_100g,protein_100g,fat_100g,carb_100g,scope,source_locale) " +
          "VALUES (?,?,?,?,?,'global',?) RETURNING id",
      )
      .bind(catId.get(f.category) ?? null, f.kcal_100g, f.protein_100g, f.fat_100g, f.carb_100g, f.source_locale)
      .first<{ id: number }>();
    foodId.set(f.name, r!.id);
    await db.prepare("INSERT INTO food_caption (food_id,locale,caption) VALUES (?,?,?)").bind(r!.id, f.source_locale, f.name).run();
  }

  for (const rc of data.recipes) {
    const r = await db
      .prepare("INSERT INTO recipe (cat1,cat2,cat3,servings,scope,source_locale) VALUES (?,?,?,?,'global',?) RETURNING id")
      .bind(rc.cat1, rc.cat2, rc.cat3, rc.servings, rc.source_locale)
      .first<{ id: number }>();
    await db.prepare("INSERT INTO recipe_caption (recipe_id,locale,caption) VALUES (?,?,?)").bind(r!.id, rc.source_locale, rc.name).run();
    let pos = 0;
    for (const ing of rc.ingredients) {
      const fid = foodId.get(ing.food);
      if (!fid) continue;
      await db
        .prepare("INSERT INTO recipe_ingredient (recipe_id,food_id,min_g,max_g,position) VALUES (?,?,?,?,?)")
        .bind(r!.id, fid, ing.min_g, ing.max_g, pos++)
        .run();
    }
  }
  return { catId, foodId };
}
